name: visita_mobile
description: "VISITA: Bohol Churches Information System - Public User Prototype"
publish_to: "none"
version: 0.1.0+1

environment:
  # Widen Dart SDK constraint to allow newer plugin versions (geolocator, etc.)
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  http: ^1.5.0
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.10
  path_provider: ^2.0.14
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^8.2.2
  photo_view: ^0.15.0
  uuid: ^4.5.1
  webview_flutter: ^4.4.2
  # Firebase dependencies
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  # New for location validation & photo uploads
  # Geolocator updated (ensure platform impl uses v2 embedding)
  geolocator: ^14.0.2
  image_picker: ^1.2.0
  carousel_slider: ^5.0.0
  # Enhanced announcements features
  intl: ^0.20.2
  # Upgraded to address Android compile ambiguity (bigLargeIcon overload)
  flutter_local_notifications: ^19.4.2
  # Enhanced profile features
  share_plus: ^12.0.0
  cached_network_image: ^3.3.0
  # Enhanced Church Exploration
  flutter_inappwebview: ^6.1.5
  # Offline capabilities
  sqflite: ^2.3.0
  connectivity_plus: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.40
  path: ^1.8.3
  crypto: ^3.0.3
  shimmer: ^3.0.0
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  # Offline database generation
  drift_dev: ^2.28.3
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/360/

## Removed dependency_overrides for geolocator_android (resolved via normal solver)
