// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCbl4Zr7nco51NJ7fRafyBOh23-2qtOD4',
    appId: '1:490423265288:web:eee490e89f588ff9bfc9bd',
    messagingSenderId: '490423265288',
    projectId: 'visitaproject-5cd9f',
    authDomain: 'visitaproject-5cd9f.firebaseapp.com',
    databaseURL: 'https://visitaproject-5cd9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'visitaproject-5cd9f.firebasestorage.app',
    measurementId: 'G-MNWKD0M7V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfenR2dQXnheuPWB2ED0kUNaBEyjsWjAE',
    appId: '1:490423265288:android:f06cbfdb7e3e4810bfc9bd',
    messagingSenderId: '490423265288',
    projectId: 'visitaproject-5cd9f',
    databaseURL: 'https://visitaproject-5cd9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'visitaproject-5cd9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1bvuDlhVeoHCopVepdgx8huYw48Urr40',
    appId: '1:490423265288:ios:cb5cdae624b4f3e7bfc9bd',
    messagingSenderId: '490423265288',
    projectId: 'visitaproject-5cd9f',
    databaseURL: 'https://visitaproject-5cd9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'visitaproject-5cd9f.firebasestorage.app',
    iosBundleId: 'com.example.visitaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyF1AtYzWsj7pH8zMs0eT2nO6qP1kH5yZ9B',
    appId: '1:490423265288:ios:d4e5f6g7h8i9j0k1',
    messagingSenderId: '490423265288',
    projectId: 'visitaproject-5cd9f',
    storageBucket: 'visitaproject-5cd9f.appspot.com',
    iosBundleId: 'com.example.visitaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVjwGfADBwbWsfQGDduS_q3qjugBYiCR0',
    appId: '1:490423265288:web:1ce925cb908a3af7bfc9bd',
    messagingSenderId: '490423265288',
    projectId: 'visitaproject-5cd9f',
    authDomain: 'visitaproject-5cd9f.firebaseapp.com',
    databaseURL: 'https://visitaproject-5cd9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'visitaproject-5cd9f.firebasestorage.app',
    measurementId: 'G-J7YX0VSMH3',
  );

}