/// FILE PURPOSE: Mobile App Entry Point - Main Application Bootstrap
///
/// This is the main entry point for the VISITA mobile application (Flutter/Dart).
/// It initializes all services, sets up dependency injection, configures themes,
/// and launches the application.
///
/// KEY RESPONSIBILITIES:
/// - Initialize Firebase for backend connectivity
/// - Set up dependency injection using Provider pattern
/// - Configure app theme (light/dark mode)
/// - Register all services and repositories
/// - Test Firebase connection on startup
/// - Launch authentication wrapper
///
/// INTEGRATION POINTS:
/// - Connects to same Firebase project as admin dashboard
/// - Uses Firestore for real-time church data
/// - Integrates Firebase Authentication for user login
/// - Configures all app-wide services and providers
///
/// TECHNICAL CONCEPTS:
/// - Flutter: Google's cross-platform mobile framework (iOS + Android)
/// - Dart: Programming language for Flutter
/// - Provider Pattern: State management and dependency injection
/// - Firebase Integration: Backend-as-a-Service connection
/// - Async Initialization: Wait for Firebase before app starts
/// - Widget Tree: Provider wraps entire app for global access
///
/// ARCHITECTURE PATTERNS:
/// - Repository Pattern: Data access abstraction
/// - Service Layer: Business logic separation
/// - Dependency Injection: Loose coupling, easy testing
/// - MVVM: Model-View-ViewModel architecture
///
/// USER TYPES (Mobile App):
/// - Public Users: Browse churches, view announcements
/// - Authenticated Users: Track visits, leave feedback
/// - No admin functions (admin features are in dashboard only)
///
/// WHY IMPORTANT:
/// - Single initialization point prevents duplicate services
/// - Provider setup enables global access to services
/// - Firebase test ensures connection before app runs
/// - Proper initialization order prevents runtime errors

import 'package:flutter/material.dart';
// Provider package for state management and dependency injection
import 'package:provider/provider.dart';
// Firebase packages for backend services
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
// Auto-generated Firebase configuration for this platform
import 'firebase_options.dart';
// Authentication wrapper (checks if user is logged in)
import 'screens/auth_wrapper.dart';
// App-wide state management
import 'models/app_state.dart';
// Repository layer: abstracts data sources
import 'repositories/church_repository.dart';
import 'repositories/announcement_repository.dart';
import 'repositories/mass_schedule_repository.dart';
import 'repositories/firestore_church_repository.dart';
import 'repositories/firestore_announcement_repository.dart';
// Service layer: business logic
import 'services/auth_service.dart';
import 'services/profile_service.dart';
import 'services/location_service.dart';
import 'services/enhanced_church_service.dart';
import 'services/local_data_service.dart';
import 'services/connectivity_service.dart';
import 'services/offline_sync_service.dart';
import 'services/paginated_church_service.dart';
// Paginated data repository for performance
import 'repositories/paginated_church_repository.dart';
// App theme configuration
import 'theme/app_theme.dart';

// Feature flag: Enable Firebase backend (true) or local data only (false)
const bool kUseFirestoreBackend = true; // Enable Firebase

/// =============================================================================
/// MAIN FUNCTION - Application Entry Point
/// =============================================================================
///
/// This is the first function called when the app launches.
///
/// INITIALIZATION SEQUENCE:
/// 1. Ensure Flutter bindings are ready (required for async operations)
/// 2. Initialize Firebase with platform-specific configuration
/// 3. Test Firestore connection to verify backend is accessible
/// 4. Launch the VisitaApp widget
///
/// WHY ASYNC:
/// - Firebase initialization requires network operations
/// - Must complete before app can access database
/// - Prevents crashes from accessing Firebase too early
///
/// ERROR HANDLING:
/// - Firebase init errors: App will crash (intentional, can't run without Firebase)
/// - Connection test errors: Logged but app continues (offline mode possible)
Future<void> main() async {
  // Must be called before using async operations in main()
  // Initializes Flutter engine and platform channels
  WidgetsFlutterBinding.ensureInitialized();

  /**
   * Initialize Firebase
   *
   * Connects to Firebase project using platform-specific configuration.
   * Configuration is auto-generated by FlutterFire CLI for each platform
   * (Android, iOS, Web).
   */
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  /**
   * Test Firestore Connection
   *
   * Performs a quick query to verify:
   * - Firebase is properly initialized
   * - Network connection is available
   * - Security rules allow read access
   * - Churches collection exists
   *
   * This helps catch configuration issues early.
   */
  try {
    final snap = await FirebaseFirestore.instance.collection('churches').get();
    debugPrint(
        '🔥 Firestore connected successfully! Found ${snap.docs.length} church documents.');
  } catch (e) {
    debugPrint('⚠️ Firestore connection test failed: $e');
    // App continues - offline mode may still work
  }

  // Launch the application
  runApp(const VisitaApp());
}

/// =============================================================================
/// VISITA APP WIDGET - Root Application Widget
/// =============================================================================
///
/// This is the root widget of the application. It sets up:
/// - Dependency injection via Provider
/// - Material Design theme
/// - App-wide services and repositories
/// - Navigation configuration
///
/// TECHNICAL CONCEPTS:
/// - StatelessWidget: Immutable widget that doesn't change
/// - MultiProvider: Registers multiple services for dependency injection
/// - Provider Types:
///   - Provider: Simple object provider (doesn't change)
///   - ChangeNotifierProvider: For reactive state (updates UI on change)
///   - ProxyProvider: Depends on other providers
///
/// PROVIDER DEPENDENCY TREE:
/// Services that depend on others are registered after their dependencies.
/// Example: PaginatedChurchService needs LocationService, so LocationService
/// is registered first.
class VisitaApp extends StatelessWidget {
  const VisitaApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    /**
     * Debug Logging
     *
     * assert() blocks only run in debug mode, not production.
     * Helps developers understand which data source is being used.
     */
    assert(() {
      debugPrint(kUseFirestoreBackend
          ? '🔥 Running with Firebase integration'
          : '📱 Running in local data mode');
      return true;
    }());

    /**
     * MultiProvider Setup
     *
     * Registers all services and repositories for dependency injection.
     * Any widget in the app can access these via:
     * - Provider.of<ServiceName>(context)
     * - context.read<ServiceName>() (one-time access)
     * - context.watch<ServiceName>() (reactive updates)
     */
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AppState()),
        ChangeNotifierProvider(create: (_) => AuthService()),
        ChangeNotifierProvider(create: (_) => ProfileService()),
        ChangeNotifierProvider(create: (_) => LocationService()),
        Provider(create: (_) => LocalDataService()),
        Provider(create: (_) => MassScheduleRepository()),

        // Mobile-only offline services
        ChangeNotifierProvider(create: (_) => ConnectivityService()),
        ChangeNotifierProvider(create: (_) => OfflineSyncService()),
        Provider(create: (_) => PaginatedChurchRepository()),
        ChangeNotifierProxyProvider<LocationService, PaginatedChurchService>(
          create: (context) => PaginatedChurchService(
            context.read<PaginatedChurchRepository>(),
            context.read<LocationService>(),
          ),
          update: (context, locationService, previous) =>
              previous ??
              PaginatedChurchService(
                context.read<PaginatedChurchRepository>(),
                locationService,
              ),
        ),

        // Data repositories - Firebase or local based on flag
        Provider<ChurchRepository>(
          create: (_) => kUseFirestoreBackend
              ? FirestoreChurchRepository()
              : ChurchRepository(),
        ),
        Provider<AnnouncementRepository>(
          create: (_) => kUseFirestoreBackend
              ? FirestoreAnnouncementRepository()
              : AnnouncementRepository(),
        ),
        ChangeNotifierProxyProvider2<LocalDataService, LocationService,
            EnhancedChurchService>(
          create: (context) => EnhancedChurchService(
            context.read<LocalDataService>(),
            context.read<LocationService>(),
          ),
          update: (context, localDataService, locationService, previous) =>
              previous ??
              EnhancedChurchService(localDataService, locationService),
        ),
      ],
      child: MaterialApp(
        title: 'VISITA - Bohol Churches',
        debugShowCheckedModeBanner: false, // Remove debug banner
        theme: buildAppTheme(Brightness.light),
        darkTheme: buildAppTheme(Brightness.dark),
        themeMode: ThemeMode.light,
        // Start with AuthWrapper so unauthenticated users see Login first
        home: const AuthWrapper(),
      ),
    );
  }
}
